default_config:

logger:
  default: warning
  logs:
    globalomnium: warning
    custom_components.globalomnium.datacoordinator: debug
    custom_components.globalomnium.sensor: debug
    custom_components.globalomnium.updates: debug
    custom_components.globalomnium.fixes: debug
    homeassistant_historical_sensor: debug
